<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TravelloLib\Module'                  => __DIR__ . '/Module.php',
    'TravelloLib\Filter\StringToUrl'      => __DIR__ . '/src/TravelloLib/Filter/StringToUrl.php',
    'TravelloLib\InputFilter\InputFilter' => __DIR__ . '/src/TravelloLib/InputFilter/InputFilter.php',
    'TravelloLib\Form\AbstractForm'       => __DIR__ . '/src/TravelloLib/Form/AbstractForm.php',
);